# command to run ansible-playbook -i inventory.yml cisco-9k.yml
# command to run ansible-playbook -i inventory.yml cisco-9k.yml --tags=show_test

---
- hosts: cat9k
  gather_facts: false
  connection: network_cli

  tasks:
  - name: Set Variables
    include_vars: vars/main.yml
    tags :
      - test
      - aaa_config
      - dhcp_config
      - sensor_config
      - cts_config
      - class_maps_config
      - policy_maps_config
      - show_commands
      - interface_config
      - clear

  - name: facts 
    ios_facts: 
      gather_subset: all

  - name: testing
    ios_config:
      src: test.j2
    tags : test

  - name: aaa_configuration part 1
    ios_config:
      src: aaa1.j2
    tags : aaa_config

  - name: aaa_configuration part 2
    ios_command:
      commands:
      - command: 'conf t'
      - command: 'aaa accounting identity default start-stop group NS-WAC-GROUP'
        prompt: '[confirm]'
        answer: 'y'
    ignore_errors: yes
    tags : aaa_config

  - name: aaa_configuration part 3
    ios_config:
      src: aaa2.j2
    tags : aaa_config

  - name : dhcp_configuration
    ios_config:
      src: dhcp.j2
    tags : dhcp_config

  - name : sensor_configuration part 1
    ios_config:
      src: sensor1.j2
    tags : sensor_config
  
  - name: sensor_configuration part 2
    ios_command:
      commands:
      - command: 'conf t'
      - command: 'access-session accounting attributes filter-spec include list DS_LIST'
        prompt: '[confirm]'
        answer: 'y'
    ignore_errors: yes
    tags : sensor_config
  
  - name : sensor_configuration part 3
    ios_config:
      src: sensor2.j2
    tags : sensor_config

  - name : cts_configuration part 1
    ios_config:
      src: cts.j2
    tags : cts_config

  - name : cts_configuration part 2
    ios_command:
      commands:
      - command: 'cts credentials id {{ variables.device_hostname }} password {{ variables.ise_password }}'
        prompt: '[confirm]'
        answer: 'y'
    ignore_errors: yes
    tags : cts_config

  - name : class_maps_configuration
    ios_config:
      src: class_maps.j2
    tags : class_maps_config
  
  - name : policy_maps_configuration
    ios_config:
      src: policy_maps.j2
    tags : policy_maps_config

  - name : interface_configuration
    ios_config:
      src: interface_config.j2
    tags : interface_config

  - name: run multiple commands
    ios_command:
      commands:
        - show cts environment-data
        - show cts pacs
        - show cts 
    register: result
    tags : show_commands

  - name: testing 2
    ios_command:
      commands:
      - command: 'conf t'
      - command: 'interface loopback99'
      - command: 'ip address 1.1.1.1 255.255.255.0'
    tags : testing2
  
  - name: save output to local directory
    copy:
      content: "{{ result.stdout | replace('\\n', '\n') }}"           
      dest: "output.txt"
    tags : show_commands
